{pkgs,...}:
let
  envExtra = ''
  '';
  # copied from the content generated by `conda init bash`
  initExtra = ''
  '';
in {
  # Homebrew's default install location:
  #   /opt/homebrew for Apple Silicon
  #   /usr/local for macOS Intel
  # The prefix /opt/homebrew was chosen to allow installations
  # in /opt/homebrew for Apple Silicon and /usr/local for Rosetta 2 to coexist and use bottles.
  programs.bash = {
    enable = true;
    bashrcExtra = envExtra + initExtra;
  };
  programs.zsh = {
    enable = true;
    inherit envExtra initExtra;
  };
  home.packages = with pkgs;[
    bandwidth
    randomize-zoom-bg
  ];
}
