#!/bin/bash

set -eo pipefail

EXIT_CODE=0
if git diff --staged --name-only | cat - <(echo /dev/null) | xargs rg "$USER"; then
    echo "Username '$USER' found in staged file!"
    EXIT_CODE=1
fi
exit "$EXIT_CODE"
