[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "grow", "--transition-pos", "top-left"]
set = true

[config.custom_keywords]
xdg_home = "$HOME/.config"
templates = "$HOME/.config/matugen/templates"
hooks = "$HOME/.config/matugen/hooks"

[templates.eww]
input_path = 'templates/eww-colors.scss.tpl'
output_path = '~/.config/eww/colors.scss'

[templates.alacritty]
input_path = 'templates/alacritty.toml.tpl'
output_path = '~/.config/alacritty/colors.toml'

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf.tpl'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = 'templates/mako-colors.toml.tpl'
output_path = '~/.config/mako/config'
post_hook = "makoctl reload"
