#!/usr/bin/env bash
bth() {
    b=${1:-0}; d=''; s=0; S=(B K M G T E P Y Z)
    while ((b > 1000)); do
        d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
        b=$((b / 1024))
        let s++
    done
    if ((b >= 100)); then
        d=''
    fi
    echo "$b$d ${S[$s]}"
}
pp() {
printf "%6s↑%6s↓" "$(bth $2)" "$(bth $1)"
}
getInterval() {
IFACE=$1
INTERVAL=$2
read -r BD BU <<<$(netstat -ib -I $IFACE | awk '/Link/{print $7,$10}')
sleep $INTERVAL
read -r AD AU <<<$(netstat -ib -I $IFACE | awk '/Link/{print $7,$10}')
DN=$(($AD - $BD))
UP=$(($AU - $BU))
pp $DN $UP
}
getInterval $1 1
