#!/usr/bin/env bash

hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id'
nc -U $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock |\
    awk -F '>>|,' -e '/^workspacev2>>/ {print $2; fflush()}' -e '/^focusedmon>>/ {print $3; fflush()}'
