#!/usr/bin/env bash
spaces (){
hyprctl clients -j |\
  jq -rc '[group_by(.workspace.id)[] |
    {
      key:.[0].workspace.id | tostring,
      value: ((map(.focusHistoryID) | min) as $f | map({address, title, class, focus: (.focusHistoryID == $f)}))
    }] |
    from_entries as $w |
    [range(1;10) | tostring |
    {id:., windows: ($w[.] // [])}]'
}

spaces
nc -U $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock |\
while read -r line; do
  spaces
done
