#!/usr/bin/env bash

set -eo pipefail

PROG=${CHAT_COMPLETION_PROGRAM:-oaichat}
TEMPLATE=${CHAT_COMPLETION_TEMPLATE:-'template://verbose_commit_message.txt'}

if command -v "$PROG" > /dev/null 2>&1; then
  DIFF=$(git diff --cached -- . ':(exclude)*lock*')

  if [ -z "$DIFF" ]; then
    exit 0
  elif [[ "${#DIFF}" -gt 32768 ]]; then
    echo "warning: git diff is too long (${#DIFF}). skipping generate."
    exit 0
  else
    mv "$1" "$1.bak"
    echo "$DIFF" | "$PROG" -s "$TEMPLATE" | cat - "$1.bak" > "$1"
    rm "$1.bak"
  fi
fi
