#!/usr/bin/env bash

set -eo pipefail

EXIT_CODE=0
git diff --staged --name-only --diff-filter=ACM | while read FILE; do
  if [[ -f "$FILE" ]]; then
    sed -i'' "s#$HOME#~#g" "$FILE"
    git add "$FILE"
  fi
done
exit "$EXIT_CODE"
