[default]
# spellchecker:disable-line
# spellchecker:<on|off>
extend-ignore-re = ["(?Rm)^.*(#|//|%|;)\\s*spellchecker:disable-line$", "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on"]
# SSL Cipher suites
extend-ignore-identifiers-re = ["\\bTLS_[A-Z0-9_]+(_anon_[A-Z0-9_]+)?\\b"]
