[default]
# spellchecker:disable-line
# spellchecker:<on|off>
extend-ignore-re = ["(?Rm)^.*(#|//|%|;)\\s*(spellcheck(er)?|typo|sc):\\s*(disable-line|ignore)$", "(?s)(#|//|%|;)\\s*(spellcheck(er)?|typo|sc):\\s*off.*?\\n\\s*(#|//|%|;)\\s*(spellcheck(er)?|typo|sc):\\s*:on"]
# SSL Cipher suites
extend-ignore-identifiers-re = ["\\bTLS_[A-Z0-9_]+(_anon_[A-Z0-9_]+)?\\b"]
