[default]
extend-ignore-re = [
  "(?Rm)^.*(#|//|%|;)\\s*(spellcheck(er)?|typo|sc):\\s*(disable-line|ignore)$", # spellchecker:disable-line
  "(?s)(#|//|%|;)\\s*(spellcheck(er)?|typo|sc):\\s*off.*?\\n\\s*(#|//|%|;)\\s*(spellcheck(er)?|typo|sc):\\s*:on", # spellchecker:<on|off>
]

extend-ignore-identifiers-re = [
  "\\bTLS_[A-Z0-9_]+(_anon_[A-Z0-9_]+)?\\b", # SSL Cipher suites
  "\\b[A-Za-z0-9+/-_]{64,}={0,2}\\b", # base64 lines
]

[files]
extend-exclude = ["*.gpg", "*.age", ".age*"]
